site_name: schnow265
site_url: https://schnow265.github.io

theme:
  name: terminal
  custom_dir: overrides
  palette: dark
  hide:
    - revision_date
    - revision_history

plugins:
  - search
  - plotly
  - drawio:
      viewer_js: "https://viewer.diagrams.net/js/viewer-static.min.js"
  - glightbox
  - blog:
      format: "(%Y-%m-%d)"
  - mktemplate

markdown_extensions:
  - attr_list
  - toc:
        permalink: "#"
        permalink_title: "Permanent Link directly to this section"
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - templates

  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

extra: 
  social:
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@schnow265