site_name: schnow265
site_url: https://schnow265.github.io

theme:
  name: terminal
  custom_dir: overrides
  palette: dark
  hide:
    - revision_date
    - revision_history

plugins:
  - search
  - plotly
  - drawio-exporter
  - glightbox
  - blog:
      format: "(%Y-%m-%d)"

markdown_extensions:
  - toc:
        permalink: "#"
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path:
        - snippets

  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
